version: '2'

services:
  tivit-monitoracao:
    build:
        context: .
        dockerfile: Dockerfile 
    image: tivit-monitoracao:1.0
    container_name: tivit-monitoracao
    hostname: tivit-monitoracao-docker
    ports:
    - "9090:9090"
    networks:
    - tivit-mon-network    
  tivit-mon-db:
    image: tivit-mon-db:1.0
    container_name: tivit-mon-db
    hostname: tivit-mon-db-docker
    ports:
    - "9010:9010"
    - "9020:9020"
    networks:
    - tivit-mon-network    
networks:
  tivit-mon-network:
    driver: bridge